const ELIGIBLE_SECTION_I = ["qcm", "exercice"];
const ELIGIBLE_CLINICAL = ["qcm", "exercice", "dossier_clinique"];

export const INTERNAT_PROGRAM = {
  methodes_analytiques_chimie_statistiques: {
    label: "Méthodes analytiques, chimie et statistiques",
    section: "I",
    officialSection: "Section I — Sciences mathématiques, physiques et chimiques",
    eligibleFor: ELIGIBLE_SECTION_I,
    description: "Méthodes analytiques, bases de chimie générale et organique, validation analytique et statistiques appliquées.",
    priority: 1,
    skills: {
      extraction_solide_liquide: "Extraction solide-liquide",
      extraction_liquide_liquide: "Extraction liquide-liquide",
      spectrophotometrie_atomique: "Spectrophotométries atomiques d'émission et d'absorption",
      spectrophotometrie_uv_visible: "Spectrophotométrie UV-visible",
      spectrofluorimetrie: "Spectrofluorimétrie moléculaire",
      chromatographie_phase_gazeuse: "Chromatographie en phase gazeuse",
      chromatographie_liquide: "Chromatographie liquide",
      electrophorese: "Méthodes électrophorétiques",
      methodes_electrochimiques: "Méthodes électrochimiques d'analyse",
      osmolarite_osmolalite: "Osmolarité et osmolalité",
      composes_chiraux: "Analyse des composés chiraux",
      fonctions_organiques: "Fonctions organiques et propriétés physico-chimiques",
      stereoisomerie: "Stéréoisomérie",
      equilibre_acide_base: "Équilibres acide-base",
      ph_pk_tampons: "pH, pK et solutions tampons",
      complexation: "Complexation",
      protometrie_non_aqueuse: "Protométrie en milieu non aqueux",
      validation_methode_analyse: "Validation d'une méthode d'analyse",
      immunoanalyse_antigene_anticorps: "Immunoanalyse antigène-anticorps",
      statistique_descriptive: "Statistique descriptive",
      intervalles_confiance: "Intervalles de confiance",
      tests_parametriques: "Tests paramétriques",
      tests_variances: "Tests de comparaison des variances",
      tests_moyennes: "Tests de comparaison des moyennes",
      tests_proportions: "Tests de comparaison des proportions",
      regression_lineaire: "Régression linéaire",
      correlation_lineaire: "Corrélation linéaire",
      chi_deux_independance: "Test du chi-deux d'indépendance",
    },
  },
  biologie_fondamentale_genetique: {
    label: "Biologie fondamentale et génétique",
    section: "II",
    officialSection: "Section II — Sciences biologiques fondamentales",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Génome humain, expression génique, transmission, mutations et diagnostics cytogénétiques ou moléculaires.",
    priority: 2,
    skills: {
      genome_humain: "Génome humain",
      expression_genes_eucaryotes: "Expression des gènes eucaryotes",
      transmission_mendelienne: "Transmission mendélienne",
      mutations_deleteres: "Mutations délétères",
      identification_mutations: "Identification des mutations",
      consequences_mutations: "Conséquences des mutations",
      caryotype: "Caryotype",
      anomalies_chromosomiques: "Anomalies chromosomiques",
      diagnostic_genetique: "Diagnostic génétique",
      diagnostic_prenatal: "Diagnostic prénatal",
    },
  },
  biochimie_metabolisme: {
    label: "Biochimie et métabolisme",
    section: "II",
    officialSection: "Section II — Sciences biologiques fondamentales",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Biochimie structurale et métabolique, enzymes, lipides, glucides, fer, os et nutrition.",
    priority: 2,
    skills: {
      activite_enzymatique: "Activité enzymatique",
      ammoniogenese: "Ammoniogenèse",
      ureogenese: "Uréogenèse",
      hemoglobines: "Hémoglobines",
      acides_nucleiques: "Acides nucléiques",
      lipoproteines: "Lipoprotéines",
      regulation_glycemie: "Régulation de la glycémie",
      metabolisme_acides_gras: "Métabolisme des acides gras",
      triglycerides: "Triglycérides",
      cholesterol: "Cholestérol",
      cetogenese: "Cétogenèse",
      metabolisme_fer: "Métabolisme du fer",
      metabolisme_osseux: "Métabolisme osseux",
      phosphocalcique: "Métabolisme phosphocalcique",
      denutrition_proteino_energetique: "Dénutrition protéino-énergétique",
    },
  },
  physiologie: {
    label: "Physiologie",
    section: "II",
    officialSection: "Section II — Sciences biologiques fondamentales",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Physiologie des grands appareils, endocrinologie, reproduction, douleur et homéostasie phosphocalcique.",
    priority: 2,
    skills: {
      physiologie_cardiovasculaire: "Physiologie cardiovasculaire",
      physiologie_respiratoire: "Physiologie respiratoire",
      physiologie_digestive: "Physiologie digestive",
      physiologie_renale: "Physiologie rénale",
      physiologie_corticosurrenales: "Physiologie des corticosurrénales",
      physiologie_thyroide: "Physiologie de la thyroïde",
      cycle_menstruel: "Cycle menstruel",
      grossesse: "Grossesse",
      douleur: "Douleur",
      physiologie_osseuse: "Physiologie osseuse",
      regulation_calcemie: "Régulation de la calcémie",
      regulation_phosphatemie: "Régulation de la phosphatémie",
    },
  },
  immunologie_fondamentale: {
    label: "Immunologie fondamentale",
    section: "II",
    officialSection: "Section II — Sciences biologiques fondamentales",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Bases cellulaires et moléculaires de l'immunité innée, adaptative et de l'inflammation.",
    priority: 2,
    skills: {
      immunoglobulines: "Immunoglobulines",
      immunite_innee: "Immunité innée",
      inflammation: "Inflammation",
      complexe_majeur_histocompatibilite: "Complexe majeur d'histocompatibilité",
      presentation_antigene: "Présentation de l'antigène",
      organes_cellules_immunitaires: "Organes et cellules immunitaires",
      reponse_humorale: "Réponse humorale",
      reponse_cellulaire: "Réponse cellulaire",
      regulation_immunitaire: "Régulation immunitaire",
    },
  },
  sante_publique_epidemiologie: {
    label: "Santé publique et épidémiologie",
    section: "III",
    officialSection: "Section III — Santé publique et environnement",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Surveillance sanitaire, prévention, vaccination, épidémiologie, droits des patients et risques associés aux soins.",
    priority: 3,
    skills: {
      surveillance_sanitaire: "Surveillance sanitaire",
      vigilances: "Vigilances sanitaires",
      prevention_sante: "Prévention en santé",
      promotion_sante: "Promotion de la santé",
      politique_vaccinale: "Politique vaccinale",
      recommandations_vaccinales: "Recommandations vaccinales",
      evaluation_vaccinale: "Évaluation vaccinale",
      conduites_addictives: "Conduites addictives",
      epidemiologie_descriptive: "Épidémiologie descriptive",
      epidemiologie_etiologique: "Épidémiologie étiologique",
      epidemiologie_evaluative: "Épidémiologie évaluative",
      depistage: "Dépistage",
      medicaments_dispositifs_hopital: "Médicaments et dispositifs médicaux à l'hôpital",
      etablissements_sante: "Établissements de santé",
      pharmacies_usage_interieur: "Pharmacies à usage intérieur",
      droits_patients: "Droits des patients",
      risque_iatrogene: "Risque iatrogène",
      risque_nosocomial: "Risque nosocomial",
    },
  },
  toxicologie_environnementale_addictologie: {
    label: "Toxicologie environnementale et addictologie",
    section: "III",
    officialSection: "Section III — Santé publique et environnement",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Toxicologie environnementale, professionnelle et substances addictives.",
    priority: 3,
    skills: {
      risques_sanitaires_eaux: "Risques sanitaires liés aux eaux",
      ethanol: "Éthanol",
      methanol: "Méthanol",
      ethylene_glycol: "Éthylène glycol",
      ethers_glycols: "Éthers de glycols",
      benzene: "Benzène",
      toluene: "Toluène",
      hydrocarbures_aromatiques_polycycliques: "Hydrocarbures aromatiques polycycliques",
      solvants_chlores: "Solvants chlorés",
      dioxines: "Dioxines",
      organophosphores: "Organophosphorés",
      carbamates: "Carbamates",
      poisons_hemolytiques: "Poisons hémolytiques",
      monoxyde_carbone: "Monoxyde de carbone",
      plomb: "Plomb",
      methemoglobinisants: "Méthémoglobinisants",
      radioelements: "Radioéléments",
      opiaces: "Opiacés",
      lsd: "LSD",
      cocaine: "Cocaïne",
      amphetaminiques: "Amphétaminiques",
      cannabis: "Cannabis",
    },
  },
  infectiologie_bacteriologie_virologie: {
    label: "Infectiologie, bactériologie et virologie",
    section: "IV",
    officialSection: "Section IV — Éléments de séméiologie et pathologie",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Syndromes infectieux, agents bactériens et viraux, résistances et conduite diagnostique.",
    priority: 4,
    skills: {
      infections_systeme_nerveux_central: "Infections du système nerveux central",
      bacteriemies: "Bactériémies",
      endocardites: "Endocardites",
      infections_urinaires: "Infections urinaires",
      infections_digestives: "Infections digestives",
      infections_orl_bronchopulmonaires: "Infections ORL et broncho-pulmonaires",
      infections_sexuellement_transmissibles: "Infections sexuellement transmissibles",
      infections_grossesse: "Infections pendant la grossesse",
      hepatites_virales: "Hépatites virales",
      infections_immunodeprime: "Infections chez l'immunodéprimé",
      staphylococcus_aureus: "Staphylococcus aureus",
      streptocoques: "Streptocoques",
      pneumocoque: "Pneumocoque",
      escherichia_coli: "Escherichia coli",
      salmonella_shigella_campylobacter: "Salmonella, Shigella et Campylobacter",
      helicobacter_pylori: "Helicobacter pylori",
      pseudomonas_aeruginosa: "Pseudomonas aeruginosa",
      haemophilus_influenzae: "Haemophilus influenzae",
      clostridium_difficile: "Clostridioides difficile",
      listeria: "Listeria",
      tuberculose: "Tuberculose",
      treponema_pallidum: "Treponema pallidum",
      chlamydia_trachomatis: "Chlamydia trachomatis",
      legionella: "Legionella",
      herpes_simplex: "Herpes simplex virus",
      cytomegalovirus: "Cytomégalovirus",
      enterovirus: "Entérovirus",
      rotavirus: "Rotavirus",
      papillomavirus: "Papillomavirus",
      grippe: "Grippe",
      rubeole: "Rubéole",
      vih: "VIH",
      sensibilite_resistance_bacteries_virus: "Sensibilité et résistance des bactéries et virus",
      mecanismes_resistance_antiinfectieux: "Mécanismes de résistance aux anti-infectieux",
    },
  },
  parasitologie_mycologie: {
    label: "Parasitologie et mycologie",
    section: "IV",
    officialSection: "Section IV — Éléments de séméiologie et pathologie",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Principales parasitoses, mycoses et méthodes diagnostiques associées.",
    priority: 4,
    skills: {
      amibiase: "Amibiase",
      giardiose: "Giardiose",
      trichomonose: "Trichomonose",
      paludisme: "Paludisme",
      toxoplasmose: "Toxoplasmose",
      leishmaniose: "Leishmaniose",
      fasciolose: "Fasciolose",
      bilharziose: "Bilharziose",
      teniasis: "Téniasis",
      hydatidose: "Hydatidose",
      oxyurose: "Oxyurose",
      anguillulose: "Anguillulose",
      candidose: "Candidose",
      cryptococcose: "Cryptococcose",
      aspergillose: "Aspergillose",
      dermatophytoses: "Dermatophytoses",
      pneumocystose: "Pneumocystose",
    },
  },
  hematologie_hemostase_transfusion: {
    label: "Hématologie, hémostase et transfusion",
    section: "IV",
    officialSection: "Section IV — Éléments de séméiologie et pathologie",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Hémopathies, cytopénies, hémostase, anticoagulation et sécurité transfusionnelle.",
    priority: 4,
    skills: {
      anemies_carentielles: "Anémies carentielles",
      anemies_hemolytiques: "Anémies hémolytiques",
      polyglobulies: "Polyglobulies",
      leucemie_myeloide_chronique: "Leucémie myéloïde chronique",
      hemophilies: "Hémophilies",
      maladie_willebrand: "Maladie de Willebrand",
      drepanocytose: "Drépanocytose",
      thalassemies: "Thalassémies",
      myelome: "Myélome",
      dysglobulinemies_monoclonales: "Dysglobulinémies monoclonales",
      leucemies_aigues: "Leucémies aiguës",
      syndromes_myelodysplasiques: "Syndromes myélodysplasiques",
      hyperlymphocytoses: "Hyperlymphocytoses",
      syndromes_mononucleosiques: "Syndromes mononucléosiques",
      leucemie_lymphoide_chronique: "Leucémie lymphoïde chronique",
      lymphomes: "Lymphomes",
      cytopenies_medicamenteuses: "Cytopénies médicamenteuses",
      thrombopenies: "Thrombopénies",
      exploration_hemostase: "Exploration de l'hémostase",
      allongement_tp_tca: "Allongement du TP et du TCA",
      surveillance_heparines: "Surveillance des héparines",
      surveillance_avk: "Surveillance des AVK",
      produits_sanguins_labiles: "Produits sanguins labiles",
      conduite_pretransfusionnelle: "Conduite prétransfusionnelle",
    },
  },
  immunopathologie_allergologie: {
    label: "Immunopathologie et allergologie",
    section: "IV",
    officialSection: "Section IV — Éléments de séméiologie et pathologie",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Pathologies inflammatoires, auto-immunes, allergiques et déficits immunitaires.",
    priority: 4,
    skills: {
      asthme: "Asthme",
      allergies: "Allergies",
      polyarthrite_rhumatoide: "Polyarthrite rhumatoïde",
      lupus_systemique: "Lupus systémique",
      deficits_immunitaires_congenitaux: "Déficits immunitaires congénitaux",
      exploration_inflammation: "Exploration de l'inflammation",
    },
  },
  pathologies_metaboliques_endocriniennes: {
    label: "Pathologies métaboliques et endocriniennes",
    section: "IV",
    officialSection: "Section IV — Éléments de séméiologie et pathologie",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Diabètes, dyslipidémies, troubles puriniques, pathologies osseuses et endocriniennes.",
    priority: 4,
    skills: {
      diabete_type_1: "Diabète de type 1",
      diabete_type_2: "Diabète de type 2",
      hyperlipoproteinemies: "Hyperlipoprotéinémies",
      hyperuricemies: "Hyperuricémies",
      troubles_metabolisme_osseux: "Troubles du métabolisme osseux",
      dysfonctionnements_thyroidiens: "Dysfonctionnements thyroïdiens",
      dysfonctionnements_corticosurrenaliens: "Dysfonctionnements corticosurrénaliens",
    },
  },
  nephrologie_equilibres_biologiques: {
    label: "Néphrologie et équilibres biologiques",
    section: "IV",
    officialSection: "Section IV — Éléments de séméiologie et pathologie",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Équilibres hydroélectrolytiques, acido-basiques, fonction rénale et adaptation thérapeutique.",
    priority: 4,
    skills: {
      troubles_hydroelectrolytiques: "Troubles hydroélectrolytiques",
      troubles_acidobasiques: "Troubles acido-basiques",
      insuffisance_renale: "Insuffisance rénale",
      syndrome_nephrotique: "Syndrome néphrotique",
      adaptation_renale_traitements: "Adaptation rénale des traitements",
      ionogramme: "Ionogramme",
      fonction_renale: "Fonction rénale",
      dfg: "Débit de filtration glomérulaire",
      hyperkaliemie: "Hyperkaliémie",
    },
  },
  hepatologie_gastroenterologie_pancreas: {
    label: "Hépatologie, gastro-entérologie et pancréas",
    section: "IV",
    officialSection: "Section IV — Éléments de séméiologie et pathologie",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Biologie hépatique, pancréas, maladie ulcéreuse et thérapeutiques digestives.",
    priority: 4,
    skills: {
      cholestase: "Cholestase",
      cytolyse_hepatique: "Cytolyse hépatique",
      insuffisance_hepatocellulaire: "Insuffisance hépatocellulaire",
      pancreatite_aigue: "Pancréatite aiguë",
      hepatites_virales_biologie: "Hépatites virales en biologie",
      ulcere_gastroduodenal: "Ulcère gastroduodénal",
      antiemetiques: "Antiémétiques",
    },
  },
  cardiologie_pathologie: {
    label: "Cardiologie clinique",
    section: "IV",
    officialSection: "Section IV — Éléments de séméiologie et pathologie",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Syndromes coronariens, insuffisance cardiaque, troubles du rythme et risque cardiovasculaire.",
    priority: 4,
    skills: {
      accidents_coronariens_aigus: "Accidents coronariens aigus",
      insuffisance_cardiaque: "Insuffisance cardiaque",
      risque_cardiovasculaire: "Risque cardiovasculaire",
      troubles_rythme: "Troubles du rythme",
      surveillance_cardiaque_traitements: "Surveillance cardiaque des traitements",
    },
  },
  neurologie_pathologie: {
    label: "Neurologie clinique",
    section: "IV",
    officialSection: "Section IV — Éléments de séméiologie et pathologie",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Pathologies neurologiques et éléments clinico-biologiques utiles aux dossiers.",
    priority: 4,
    skills: {
      epilepsie: "Épilepsie",
      migraines: "Migraines",
      algies_faciales: "Algies faciales",
      maladie_alzheimer: "Maladie d'Alzheimer",
      maladie_parkinson: "Maladie de Parkinson",
      sclerose_en_plaques: "Sclérose en plaques",
    },
  },
  sciences_medicament_pharmacologie_generale: {
    label: "Sciences du médicament — pharmacologie générale",
    section: "V",
    officialSection: "Section V — Sciences du médicament",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Pharmacocinétique, pharmacodynamie, cibles, formes, indications, sécurité et interactions.",
    priority: 5,
    skills: {
      absorption_resorption: "Absorption et résorption",
      distribution: "Distribution",
      biotransformation: "Biotransformation",
      excretion: "Excrétion",
      facteurs_physiologiques: "Facteurs physiologiques influençant le médicament",
      etats_pathologiques: "États pathologiques influençant le médicament",
      xenobiotiques_associes: "Xénobiotiques associés",
      biodisponibilite: "Biodisponibilité",
      parametres_pharmacocinetiques: "Paramètres pharmacocinétiques",
      cibles_medicaments: "Cibles des médicaments",
      recepteurs: "Récepteurs",
      liaison_recepteur: "Liaison au récepteur",
      courbe_effet_dose: "Courbe effet-dose",
      dose_efficace_50: "Dose efficace 50",
      marge_therapeutique: "Marge thérapeutique",
      denomination_commune_internationale: "Dénomination commune internationale",
      relation_structure_activite: "Relation structure-activité",
      mecanisme_action: "Mécanisme d'action",
      indications_amm: "Indications et AMM",
      formes_galeniques: "Formes galéniques",
      precautions_emploi: "Précautions d'emploi",
      contre_indications: "Contre-indications",
      effets_indesirables: "Effets indésirables",
      interactions_medicamenteuses: "Interactions médicamenteuses",
    },
  },
  sciences_medicament_neurologie_psychiatrie: {
    label: "Sciences du médicament — neurologie et psychiatrie",
    section: "V",
    officialSection: "Section V — Sciences du médicament",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Médicaments du système nerveux, psychotropes, antalgiques et traitements neurologiques spécialisés.",
    priority: 5,
    skills: {
      medicaments_epilepsie: "Médicaments de l'épilepsie",
      medicaments_migraine: "Médicaments de la migraine",
      medicaments_algies_faciales: "Médicaments des algies faciales",
      medicaments_alzheimer: "Médicaments de la maladie d'Alzheimer",
      medicaments_parkinson: "Médicaments de la maladie de Parkinson",
      medicaments_sclerose_plaques: "Médicaments de la sclérose en plaques",
      antalgiques: "Antalgiques",
      antipsychotiques: "Antipsychotiques",
      anxiolytiques: "Anxiolytiques",
      hypnotiques: "Hypnotiques",
      antidepresseurs: "Antidépresseurs",
      normothymiques: "Normothymiques",
    },
  },
  sciences_medicament_cardiologie_hemostase: {
    label: "Sciences du médicament — cardiologie et hémostase",
    section: "V",
    officialSection: "Section V — Sciences du médicament",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Médicaments cardiovasculaires, anticoagulants, antiagrégants et traitements de l'hémostase.",
    priority: 5,
    skills: {
      medicaments_insuffisance_cardiaque: "Médicaments de l'insuffisance cardiaque",
      anti_angoreux: "Anti-angoreux",
      antihypertenseurs: "Antihypertenseurs",
      diuretiques: "Diurétiques",
      anticoagulants: "Anticoagulants",
      antiagregants_plaquettaires: "Antiagrégants plaquettaires",
      thrombolytiques: "Thrombolytiques",
      solutes_remplissage_vasculaire: "Solutés de remplissage vasculaire",
      antiarythmiques: "Antiarythmiques",
      medicaments_troubles_rythme: "Médicaments des troubles du rythme",
    },
  },
  sciences_medicament_pneumologie_inflammation: {
    label: "Sciences du médicament — pneumologie, allergologie et inflammation",
    section: "V",
    officialSection: "Section V — Sciences du médicament",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Médicaments de l'asthme, de l'allergie et de l'inflammation.",
    priority: 5,
    skills: {
      antiasthmatiques: "Antiasthmatiques",
      antiallergiques: "Antiallergiques",
      anti_inflammatoires: "Anti-inflammatoires",
    },
  },
  sciences_medicament_metabolisme_endocrinologie: {
    label: "Sciences du médicament — métabolisme et endocrinologie",
    section: "V",
    officialSection: "Section V — Sciences du médicament",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Médicaments du métabolisme glucidique, lipidique, osseux, thyroïdien et de la goutte.",
    priority: 5,
    skills: {
      medicaments_goutte: "Médicaments de la goutte",
      antidiabetiques_oraux: "Antidiabétiques oraux",
      insulines: "Insulines",
      medicaments_thyroide: "Médicaments de la thyroïde",
      normolipemiants: "Normolipémiants",
      medicaments_osteoporose: "Médicaments de l'ostéoporose",
    },
  },
  sciences_medicament_antiinfectieux: {
    label: "Sciences du médicament — anti-infectieux",
    section: "V",
    officialSection: "Section V — Sciences du médicament",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Antibactériens, antiviraux, antifongiques, antiparasitaires et traitements des infections majeures.",
    priority: 5,
    skills: {
      sulfamides_antibacteriens: "Sulfamides antibactériens",
      betalactamines: "Bêtalactamines",
      macrolides: "Macrolides",
      cyclines: "Cyclines",
      aminosides: "Aminosides",
      glycopeptides: "Glycopeptides",
      quinolones: "Quinolones",
      antituberculeux: "Antituberculeux",
      antiretroviraux: "Antirétroviraux",
      antiviraux_hepatites: "Antiviraux des hépatites",
      antiviraux_grippe: "Antiviraux de la grippe",
      antiviraux_herpes: "Antiviraux de l'herpès",
      antifongiques_generaux: "Antifongiques généraux",
      antiprotozoaires_intestinaux: "Antiprotozoaires intestinaux",
      anthelminthiques_intestinaux: "Anthelminthiques intestinaux",
      antimalariques: "Antimalariques",
    },
  },
  sciences_medicament_gastroenterologie: {
    label: "Sciences du médicament — gastro-entérologie",
    section: "V",
    officialSection: "Section V — Sciences du médicament",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Médicaments de l'ulcère gastroduodénal et antiémétiques.",
    priority: 5,
    skills: {
      medicaments_ulcere_gastroduodenal: "Médicaments de l'ulcère gastroduodénal",
      antiemetiques: "Antiémétiques",
    },
  },
  sciences_medicament_immunologie_oncologie: {
    label: "Sciences du médicament — immunologie, hématologie et oncologie",
    section: "V",
    officialSection: "Section V — Sciences du médicament",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Immunosuppresseurs, cytokines, facteurs de croissance, anticancéreux et soins associés.",
    priority: 5,
    skills: {
      immunosuppresseurs: "Immunosuppresseurs",
      facteurs_croissance_hematopoietiques: "Facteurs de croissance hématopoïétiques",
      cytokines: "Cytokines",
      antagonistes_cytokines: "Antagonistes des cytokines",
      anticancereux: "Anticancéreux",
      traitements_associes_cancer: "Traitements associés du cancer",
    },
  },
  sciences_medicament_toxicologie: {
    label: "Sciences du médicament — toxicologie médicamenteuse",
    section: "V",
    officialSection: "Section V — Sciences du médicament",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Toxicologie des médicaments, organotoxicités, psychotropes, antidotes et prise en charge des intoxications.",
    priority: 5,
    skills: {
      evaluation_toxicite_medicament: "Évaluation de la toxicité d'un médicament",
      toxicologie_systemique: "Toxicologie systémique",
      toxicite_hematologique: "Toxicité hématologique",
      toxicite_hepatique: "Toxicité hépatique",
      toxicite_renale: "Toxicité rénale",
      toxicite_cardiovasculaire: "Toxicité cardiovasculaire",
      toxicite_pulmonaire: "Toxicité pulmonaire",
      toxicologie_psychotropes: "Toxicologie des psychotropes",
      lithium: "Lithium",
      benzodiazepines: "Benzodiazépines",
      carbamates: "Carbamates",
      neuroleptiques: "Neuroleptiques",
      antidepresseurs_toxicologie: "Antidépresseurs en toxicologie",
      salicyles: "Salicylés",
      paracetamol: "Paracétamol",
      morphinomimetiques: "Morphinomimétiques",
      digoxine: "Digoxine",
      chloroquine: "Chloroquine",
      traitement_intoxications: "Traitement des intoxications",
      antidotes: "Antidotes",
    },
  },
  sciences_medicament_galenique_biotherapies: {
    label: "Sciences du médicament — galénique, vaccins et biothérapies",
    section: "V",
    officialSection: "Section V — Sciences du médicament",
    eligibleFor: ELIGIBLE_CLINICAL,
    description: "Procédés stériles, formes pharmaceutiques, médicaments dérivés du plasma, vaccins et biomédicaments.",
    priority: 5,
    skills: {
      sterilisation: "Stérilisation",
      conditionnement_aseptique: "Conditionnement aseptique",
      formes_orales_conventionnelles: "Formes orales conventionnelles",
      formes_parenterales_conventionnelles: "Formes parentérales conventionnelles",
      formes_liberation_modifiee: "Formes à libération modifiée",
      formes_distribution_modifiee: "Formes à distribution modifiée",
      nutrition_parenterale: "Nutrition parentérale",
      formes_nasales: "Formes nasales",
      formes_pulmonaires: "Formes pulmonaires",
      formes_cutanees: "Formes cutanées",
      formes_transdermiques: "Formes transdermiques",
      formes_oculaires: "Formes oculaires",
      medicaments_derives_plasma: "Médicaments dérivés du plasma",
      albumine: "Albumine",
      facteurs_hemostase: "Facteurs de l'hémostase",
      immunoglobulines: "Immunoglobulines",
      vaccins_hepatite_b: "Vaccins contre l'hépatite B",
      vaccin_ror: "Vaccin ROR",
      vaccin_tetanos: "Vaccin tétanos",
      vaccin_grippe: "Vaccin grippe",
      anticorps_monoclonaux: "Anticorps monoclonaux",
      cellules_souches_hematopoietiques: "Cellules souches hématopoïétiques",
    },
  },
};

export const PROGRAM_OPTIONS = Object.entries(INTERNAT_PROGRAM).map(([id, item]) => ({
  id,
  label: item.label,
}));

export function getProgramSubject(subjectId) {
  return INTERNAT_PROGRAM[subjectId] || INTERNAT_PROGRAM.sciences_medicament_pharmacologie_generale;
}

export function getSkillLabel(skillId) {
  const rawSkillId = String(skillId || "");
  if (!rawSkillId) return rawSkillId;

  const parts = rawSkillId.split(".");
  const subject = INTERNAT_PROGRAM[parts[0]];
  if (subject) {
    const directKey = parts.slice(1).join(".");
    const underscoredKey = parts.slice(1).join("_");
    if (subject.skills[directKey]) return subject.skills[directKey];
    if (subject.skills[underscoredKey]) return subject.skills[underscoredKey];
  }

  for (const item of Object.values(INTERNAT_PROGRAM)) {
    if (item.skills[rawSkillId]) return item.skills[rawSkillId];
    for (let index = 1; index < parts.length; index += 1) {
      const candidate = parts.slice(index).join("_");
      if (item.skills[candidate]) return item.skills[candidate];
    }
  }

  return rawSkillId;
}

export function getProgramsByExamType(examType) {
  return Object.entries(INTERNAT_PROGRAM)
    .filter(([, item]) => item.eligibleFor?.includes(examType))
    .map(([id, item]) => ({ id, label: item.label }));
}

export function getSkillsForExamType(examType) {
  return Object.entries(INTERNAT_PROGRAM)
    .filter(([, item]) => item.eligibleFor?.includes(examType))
    .flatMap(([subjectId, subject]) =>
      Object.entries(subject.skills).map(([skillKey, label]) => ({
        subjectId,
        subjectLabel: subject.label,
        skillId: `${subjectId}.${skillKey}`,
        skillKey,
        label,
      })),
    );
}
